# Generated by Django 5.2.3 on 2025-11-03 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_posts_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
